# Generated by Django 2.1.7 on 2020-02-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('is_delete', models.BooleanField(default=0, verbose_name='删除数值')),
            ],
            options={
                'verbose_name': '用户信息',
                'db_table': 'tb_user',
            },
        ),
    ]
